### ISSUE TITLE
Subscription validation pop-up does not disappear

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/vaadin-login#52] opened 2018-12-17 08:15 UTC
Expected: either there's no subscription validation since the license is Apache 2.0 (https://github.com/vaadin/vaadin-login/blob/master/LICENSE) or subscription validation dialog disappears after first successful validation

Actual:
![image](https://user-images.githubusercontent.com/2690773/50074435-937b1880-01e4-11e9-80c2-3eb170fa7377.png)

every time I open the page, no matter how many times I click on the pop-up

**Comment by tulioag** [comment] 2019-01-07 14:52
I was unable to reproduce. I did the following:

1. Created a new project using polymer init
2. Instaled vaadin-login. Tried with both `bower i vaadin-login` and  `bower i vaadin-login#master`
3. Added  `<vaadin-login-overlay opened></vaadin-login-overlay>` to the application.

@SomeoneToIgnore , is this the correct way to reproduce this?

**Comment by SomeoneToIgnore** [comment] 2019-01-07 14:53
Just double checked on our project and looks like the pop-up is gone.
Guess the issue can be closed.

**Comment by tulioag** [comment] 2019-01-07 14:58
Thanks for looking into this! I will close the issue then.

**Closed by tulioag** 2019-01-07 14:58 UTC
